# Generated by Django 4.0.1 on 2022-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=2, null=True)),
                ('prova1', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('lista1', models.IntegerField(default=0)),
                ('lista2', models.IntegerField(default=0)),
                ('prova2', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('lista3', models.IntegerField(default=0)),
                ('lista4', models.IntegerField(default=0)),
                ('prova3', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('lista5', models.IntegerField(default=0)),
                ('lista6', models.IntegerField(default=0)),
                ('prova4', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('lista7', models.IntegerField(default=0)),
                ('lista8', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ab1', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('ab2', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('reav', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('final', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('situacao', models.CharField(default='EM ANÁLISE', max_length=20)),
            ],
        ),
    ]
