# Generated by Django 4.0.1 on 2022-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='prova1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
