# Generated by Django 4.0.1 on 2022-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_alter_aluno_prova1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='prova2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='prova3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='prova4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notaaluno',
            name='ab1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notaaluno',
            name='ab2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notaaluno',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notaaluno',
            name='reav',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
