# Generated by Django 4.0.1 on 2022-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0003_alter_aluno_prova2_alter_aluno_prova3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaaluno',
            name='mediaFinal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
