# Generated by Django 4.0.1 on 2022-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0004_notaaluno_mediafinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='lista1',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista2',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista3',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista4',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista5',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista6',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista7',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lista8',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=4),
        ),
    ]
