# Generated by Django 4.0.1 on 2022-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0005_alter_aluno_lista1_alter_aluno_lista2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaaluno',
            name='turma',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
