# Generated by Django 4.0.1 on 2022-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0006_notaaluno_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='id_huxley',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notaaluno',
            name='id_huxley',
            field=models.IntegerField(default=0),
        ),
    ]
