# Generated by Django 4.1 on 2022-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0007_aluno_id_huxley_notaaluno_id_huxley'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAttNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=150)),
            ],
        ),
    ]
