# Generated by Django 4.2 on 2023-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0009_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='id_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_reav',
            field=models.IntegerField(default=0),
        ),
    ]
